version: "2.1"
services:
  transmission:
    image: chisbread/transmission
    container_name: transmission_baocun
    networks:
      macvlan_ikuai:
        ipv4_address: 192.168.1.202
    environment:
      - USER=lumen
      - PASS=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - /hdd/pt_baocun:/downloads
      - /hdd/pt_baocun/to_download_torr:/watch
    # ports:
    #   - 9090:9091
    #   - 52413:51413
    #   - 52413:51413/udp
    restart: unless-stopped
networks:
  macvlan_ikuai:
    external:
      name: ikuai
